project_tracker/project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
# from quality_control.views import index


urlpatterns = [
    path('', include('tasks.urls')),
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls'))
]

project_tracker/quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [

    # READ
    # path('', views.index, name='index'),
    # path('bugs/', views.bugs_list, name='bugs_list'),
    # path('features/', views.features_list, name='features_list'),
    # path('bugs/<int:bug_id>/', views.bug_detail, name='bug_detail'),
    # path('features/<int:feature_id>/', views.feature_id_detail, name='feature_detail'),

    path('', views.IndexView.as_view(), name='index'),
    path('bugs/', views.BugsListView.as_view(), name='bugs_list'),
    path('features/', views.FeaturesListView.as_view(), name='features_list'),
    path('bugs/<int:bug_id>/', views.BugDetailView.as_view(), name='bug_detail'),
    path('features/<int:feature_id>/', views.FeatureDetailView.as_view(), name='feature_detail'),

    #CREATE
    # path('bugs/new/', views.add_bug_report, name='bug_report_form'),
    # path('features/new/', views.add_feature_request, name='feature_list_form'),

    path('bugs/new/', views.BugCreateView.as_view(), name='bug_report_form'),
    path('features/new/', views.FeatureCreateView.as_view(), name='feature_list_form'),

    # UPDATE
    # path('bugs/<int:bug_id>/update/', views.update_bug, name='update_bug'),
    # path('features/<int:feature_id>/update/', views.update_feature, name='update_feature'),

    path('bugs/<int:bug_id>/update/', views.BugUpdateView.as_view(), name='update_bug'),
    path('features/<int:feature_id>/update/', views.FeatureUpdateView.as_view(), name='update_feature'),

    # DELETE
    # path('bugs/<int:bug_id>/delete/', views.delete_bug, name='delete_bug'),
    # path('features/<int:feature_id>/delete/', views.delete_feature, name='delete_feature'),

    path('bugs/<int:bug_id>/delete/', views.BugDeleteView.as_view(), name='delete_bug'),
    path('features/<int:feature_id>/delete/', views.FeatureDeleteView.as_view(), name='delete_feature'),
]

project_tracker/tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [

    # READ
    # path('', views.index),
    # path('projects/', views.projects_list, name='projects_list'),
    # path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),

    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),

    # CREATE
    path('feedback/', views.feedback_view, name='feedback'),
    # path('project/create/', views.create_project, name='create_project'),
    # path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),

    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),

    # UPDATE
    # path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    # path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),

    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),

    # DELETE
    # path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    # path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),

    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
]

project_tracker/quality_control/models.py
from django.db import models

from tasks.models import Project, Task


# Create your models here.


class BugReport(models.Model):
    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена'),
    ]
    BUG_PRIORITY = [
        ('1', 'Дедлайн 1 год'),
        ('2', 'Дедлайн 1 квартал'),
        ('3', 'Дедлайн 1 месяц'),
        ('4', 'Дедлайн 1 неделя'),
        ('5', 'Дедлайн 1 день'),
    ]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(  # А это точно из tasks? А если я Project создам в quality_control?
        Project,
        related_name='bugs',  # надо ли это оставлять?
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,
        null=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New',
    )
    priority = models.CharField(  # Следует ли сделать так или можно по-другому?
        max_length=50,
        choices=BUG_PRIORITY,
        default='1',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeatureRequest(models.Model):
    STATUS_CHOICES = [  # Нормально ли обзывать разные вещи в разных классах одним и тем же именем?
        ('Review', 'На рассмотрении'),
        ('Accepted', 'Принято в обработку'),
        ('Declined', 'Отклонено'),
    ]
    REQUEST_PRIORITY = [
        ('1', 'Дедлайн 1 год'),
        ('2', 'Дедлайн 1 квартал'),
        ('3', 'Дедлайн 1 месяц'),
        ('4', 'Дедлайн 1 неделя'),
        ('5', 'Дедлайн 1 день'),
    ]
    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        related_name='request',  # надо ли это оставлять?
        on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        on_delete=models.SET_NULL,  # это так делается или нет?
        null=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='New',
    )
    priority = models.CharField(  # Следует ли сделать так или можно по-другому?
        max_length=50,
        choices=REQUEST_PRIORITY,
        default='1',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

project_tracker/quality_control/forms.py
from django import forms
from django.forms import ModelForm
from tasks.models import Project, Task
from .models import BugReport, FeatureRequest


class BugReportForm(forms.ModelForm):
    class Meta:
        model = BugReport
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']


class FeatureRequestForm(forms.ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title', 'description', 'status', 'priority', 'project', 'task']

project_tracker/quality_control/views.py
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from .models import BugReport, FeatureRequest
from tasks.models import Project, Task
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, ListView, CreateView
from django.views import View
from .forms import BugReportForm, FeatureRequestForm
from django.views.generic.edit import UpdateView, DeleteView



def index(request):
    return render(request, 'quality_control/index.html')


# def index(request):
#     bugs_url = reverse('quality_control:bug_list')
#     feature_url = reverse('quality_control:feature_list')
#     html = f'''
#     <h1>Система контроля качества</h1>
#     <ul>
#         <li>
#             <a href='{bugs_url}'>Список всех багов</a>
#         </li>
#         <li>
#             <a href='{feature_url}'>Запросы на улучшение</a>
#         </li>
#     </ul>
# '''
#     return HttpResponse(html)


def bugs_list(request):
    bug = BugReport.objects.all()
    return render(request, 'quality_control/bugs_list.html', {'bugs_list': bug})

# def bug_list(request):
#     bugs = BugReport.objects.all()
#     bugs_html = '<h1>Список всех багов</h1><ul>'
#     for bug in bugs:
#         bugs_html += f'''
#         <li>
#             <a href="{bug.id}/">{bug.title}</a>
#             <br>
#             <pre>  Status: {bug.status}</pre>
#         </li>
#         '''
#     bugs_html += '</ul>'
#     return HttpResponse(bugs_html)


def features_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/features_list.html', {'features_list': features})


# def feature_list(request):
#     features = FeatureRequest.objects.all()
#     features_html = '<h1>Список всех запросов на улучшение</h1><ul>'
#     for feature in features:
#         features_html += f'''
#             <li>
#                 <a href="{feature.id}/">{feature.title}</a>
#                 <br>
#                 <pre>  Status: {feature.status}</pre>
#             </li>
#             '''
#     features_html += '</ul>'
#     return HttpResponse(features_html)


def bug_detail(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    return render(request, 'quality_control/bug_detail.html', {'bug': bug})


def feature_id_detail(request, feature_id):
    feature = get_object_or_404(FeatureRequest, id=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'feature': feature})


class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')


# class IndexView(View):
#     def get(self, request, *args, **kwargs):
#         bugs_url = reverse('quality_control:bug_list')
#         feature_url = reverse('quality_control:feature_list')
#         html = f'''
#             <h1>Система контроля качества</h1>
#             <ul>
#                 <li>
#                     <a href='{bugs_url}'>Список всех багов</a>
#                 </li>
#                 <li>
#                     <a href='{feature_url}'>Запросы на улучшение</a>
#                 </li>
#             </ul>
#         '''
#         return HttpResponse(html)


class BugsListView(ListView):
    model = BugReport
    context_object_name = "bugs_list"
    template_name = 'quality_control/bugs_list.html'


class FeaturesListView(ListView):
    model = FeatureRequest
    context_object_name = "features_list"
    template_name = 'quality_control/features_list.html'


class BugDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    context_object_name = "bug"
    template_name = 'quality_control/bug_detail.html'


# class BugDetailView(DetailView):
#     model = BugReport
#     pk_url_kwarg = 'bug_id'
#
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         bug = self.object
#         response_html = f'''
#         <h1><pre><strong>Title:</strong>  {bug.title}</pre></h1>
#         <p>
#             <pre><strong>Description:</strong> {bug.description}</pre>
#         </p>
#         <p>
#             <pre><strong>Status:</strong>  {bug.status}</pre>
#         </p>
#         <p>
#             <pre><strong>Priority:</strong>  {bug.priority}</pre>
#         </p>
#         <p>
#             <pre><strong>Находится в проекте:</strong>  {bug.project}</pre>
#         </p>
#         <p>
#             <pre><strong>Относится к задаче:</strong>  {bug.task}</pre>
#         </p>
#         '''
#         return HttpResponse(response_html)


class FeatureDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    context_object_name = "feature"
    template_name = 'quality_control/feature_detail.html'


# class FeatureDetailView(DetailView):
#     model = FeatureRequest
#     pk_url_kwarg = 'feature_id'
#
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         feature = self.object
#         response_html = f'''
#         <h1><pre><strong>Title:</strong>  {feature.title}</pre></h1>
#         <p>
#             <pre><strong>Description:</strong> {feature.description}</pre>
#         </p>
#         <p>
#             <pre><strong>Status:</strong>  {feature.status}</pre>
#         </p>
#         <p>
#             <pre><strong>Priority:</strong>  {feature.priority}</pre>
#         </p>
#         <p>
#             <pre><strong>Находится в проекте:</strong>  {feature.project}</pre>
#         </p>
#         <p>
#             <pre><strong>Относится к задаче:</strong>  {feature.task}</pre>
#         </p>
#         '''
#         return HttpResponse(response_html)


def add_bug_report(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bugs_list')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_report_form.html', {'form': form})


def add_feature_request(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:features_list')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_request_form.html', {'form': form})


class BugCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_form.html'
    success_url = reverse_lazy('quality_control:bugs_list')


class FeatureCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_form.html'
    success_url = reverse_lazy('quality_control:features_list')


def update_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_detail', bug_id=bug.id)
    else:
        form = BugReportForm(instance=bug)
    return render(request, 'quality_control/bug_report_update.html', {'form': form, 'bug': bug})


def update_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_detail', feature_id=feature.id)
    else:
        form = FeatureRequestForm(instance=feature)
    return render(request, 'quality_control/feature_request_update.html', {'form': form, 'feature': feature})


class BugUpdateView(DetailView, UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_report_update.html'
    pk_url_kwarg = 'bug_id'

    def get_success_url(self):
        return reverse_lazy('quality_control:bug_detail', kwargs={'bug_id': self.object.id})


class FeatureUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_request_update.html'
    pk_url_kwarg = 'feature_id'

    def get_success_url(self):
        return reverse_lazy('quality_control:feature_detail', kwargs={'feature_id': self.object.id})


def delete_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    bug.delete()
    return redirect('quality_control:bugs_list')


def delete_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    feature.delete()
    return redirect('quality_control:features_list')


class BugDeleteView(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    context_object_name = "bug"
    success_url = reverse_lazy('quality_control:bugs_list')
    template_name = 'quality_control/bug_confirm_delete.html'


class FeatureDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    context_object_name = "feature"
    success_url = reverse_lazy('quality_control:features_list')
    template_name = 'quality_control/feature_confirm_delete.html'

project_tracker/quality_control/templates/quality_control/bug_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление бага</h1>
    <p>Вы уверены, что хотите удалить баг? "{{ bug.title }}"?</p>

    <form action="{% url 'quality_control:delete_bug' bug.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bug_detail' bug.id %}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1><strong>Title:</strong> {{ bug.title }}</h1>
        <p><strong>Description:</strong> {{ bug.description }}</p>
        <p><strong>Status:</strong> {{ bug.status }}</p>
        <p><strong>Priority:</strong> {{ bug.priority }}</p>
        <p><strong>Находится в проекте:</strong> {{ bug.project }}</p>
        <p><strong>Относится к задаче:</strong> {{ bug.task }}</p>

    <p><a href="{% url 'quality_control:update_bug' bug.id %}">Изменить отчёт об ошибке</a></p>

    <p><a href="{% url 'quality_control:delete_bug' bug.id %}"onclick="return confirm('Вы уверены, что хотите удалить эту ошибку?');">Удалить ошибку</a></p>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_report_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Сообщить об ошибке</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bug_report_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменить сообщение об ошибке: {{ bug.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/bugs_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список всех багов</h1>
    <ul>
        {% for bug in bugs_list %}
        <li>
            <a href="{% url 'quality_control:bug_detail' bug.id %}">{{ bug.title }}</a>
            <br>
            <pre>  Status: {{ bug.status }}</pre>
        </li>
        {% endfor %}
    </ul>
    <br><br>
        <a href="{% url 'quality_control:bug_report_form' %}">Сообщить об ошибке</a>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить запрос на улучшение? "{{ feature.title }}"?</p>

    <form action="{% url 'quality_control:delete_feature' feature.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feature_detail' feature.id %}">Отмена</a>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1><strong>Title:</strong> {{ feature.title }}</h1>
        <p><strong>Description:</strong> {{ feature.description }}</p>
        <p><strong>Status:</strong> {{ feature.status }}</p>
        <p><strong>Priority:</strong> {{ feature.priority }}</p>
        <p><strong>Находится в проекте:</strong> {{ feature.project }}</p>
        <p><strong>Относится к задаче:</strong> {{ feature.task }}</p>

    <p><a href="{% url 'quality_control:update_feature' feature.id %}">Изменить предложение об улучшении</a></p>

    <p><a href="{% url 'quality_control:delete_feature' feature.id %}"onclick="return confirm('Вы уверены, что хотите удалить это предложение об улучшении?');">Удалить предложение об улучшении</a></p>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_request_form.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Предложить улучшение</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/feature_request_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменить предложение по улучшению: {{ feature.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}

project_tracker/quality_control/templates/quality_control/features_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Список всех запросов на улучшение</h1>

    <ul>
        {% for feature in features_list %}
            <li>
                <a href="{% url 'quality_control:feature_detail' feature.id %}">{{ feature.title }}</a>
                <br>
                Status: {{ feature.status }}
            </li>
        {% endfor %}
    </ul>
    <br><br>
        <a href="{% url 'quality_control:feature_list_form' %}">Предложить улучшение</a>
{% endblock %}

project_tracker/quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block content %}
        <h1>Система контроля качества</h1>
        <a href="{% url 'quality_control:bugs_list' %}">Список всех багов</a>
        <br>
        <a href="{% url 'quality_control:features_list' %}">Запросы на улучшение</a>
        <br><br>
        <a href="{% url 'quality_control:bug_report_form' %}">Сообщить об ошибке</a>
        <br>
        <a href="{% url 'quality_control:feature_list_form' %}">Предложить улучшение</a>
{% endblock %}